BoardSystem/Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BoardSystem.DataContext;
using BoardSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BoardSystem.Controllers
{
    public class BoardController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            if(HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }

            List<Board> list;
            try
            {
                list = getList(0);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
            
            return View(list);
        }

        public JsonResult Paging(int page)
        {
            List<Board> list = null;
            try
            {
                list = getList(page);
            }
            catch
            {
                //return RedirectToAction("Error", "Home");
            }

            JArray json = new JArray();
            foreach(Board board in list)
            {
                String jori = "{";
                jori += "\"No\":\"" + board.BoardNum + "\",";
                jori += "\"Title\":\"" + board.BoardTitle + "\",";
                jori += "\"User\":\"" + board.UserId + "\",";
                jori += "\"Date\":\"" + board.BoardDate + "\",";
                jori += "\"Views\":\"" + board.BoardViews + "\"";
                jori += "}";
                JObject jtmp = JObject.Parse(jori);
                json.Add(jtmp);
            }

            return new JsonResult(json);
            //return View(list);
        }

        private List<Board> getList(int page)
        {
            using (var db = new BoardSystemContext())
            {
                List<Board> list;
                if (page == 0)
                {
                    list = db.Boards.OrderByDescending(s => s.BoardNum).Take(20).ToList();
                }
                else
                {
                    list = db.Boards.OrderByDescending(s => s.BoardNum).Skip(20 + (page - 1) * 10).Take(10).ToList();
                }

            return list;
            }
        }

        public IActionResult Detail(int boardNum)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            using (var db = new BoardSystemContext())
            {
                Board board;
                IEnumerable<Comment> commentList;
                try
                {
                    board = db.Boards.FirstOrDefault(n => n.BoardNum.Equals(boardNum));
                    db.Entry(board).Entity.BoardViews = board.BoardViews + 1;
                    db.SaveChanges();
                    commentList = db.Comments.ToList().Where(d => d.BoardNum.Equals(boardNum));
                    ViewBag.commentList = commentList;
                } catch {
                    return RedirectToAction("Error", "Home");
                }
                
                return View(board);
            }
        }

        public IActionResult Add()
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Add(Board model)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            model.UserId = HttpContext.Session.GetString("USER_LOGIN_KEY");

            if (ModelState.IsValid)
            {
                using (var db = new BoardSystemContext())
                {
                    try
                    {
                        db.Boards.Add(model);

                        if (db.SaveChanges() > 0)
                        {
                            return Redirect("Index");
                        }
                    }
                    catch
                    {
                        return RedirectToAction("Error", "Home");
                    }
                    
                }
                ModelState.AddModelError(string.Empty, "投稿できません。");
            }
            return View(model);
        }

        public IActionResult Edit()
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

    
        public IActionResult Delete(int boardNum)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            using (var db = new BoardSystemContext())
            {
                Board board;
                try
                {
                    board = db.Boards.Find(boardNum);
                    db.Boards.Remove(board);
                    db.SaveChanges();
                }
                catch
                {
                    return RedirectToAction("Error", "Home");
                }
                
                return Redirect("Index");
            }
        }

        public IActionResult DeleteComment(int boardNum, int commentNum)
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            using (var db = new BoardSystemContext())
            {
                Comment comment;
                try
                {
                    comment = db.Comments.Find(commentNum);
                    db.Comments.Remove(comment);
                    db.SaveChanges();
                }
                catch
                {
                    return RedirectToAction("Error", "Home");
                }
                return Redirect("Detail?boardNum=" + boardNum);
            }
        }

        [HttpPost]
        [ActionName("AddComment")]
        public IActionResult AddComment()
        {
            if (HttpContext.Session.GetString("USER_LOGIN_KEY") == null)
            {
                return RedirectToAction("Login", "Account");
            }
            string commentContents = Request.Form["CommentContents"].ToString();
            string userId = Request.Form["UserId"].ToString();
            int boardNum = int.Parse(Request.Form["BoardNum"].ToString());
            Comment comment = new Comment
            {
                BoardNum = boardNum,
                CommentContents = commentContents,
                UserId = userId
            };
            using (var db = new BoardSystemContext())
            {
                try
                {
                    db.Comments.Add(comment);
                    db.SaveChanges();
                }
                catch
                {
                    return RedirectToAction("Error", "Home");
                }
                
                return Redirect("Detail?boardNum="+ boardNum);
            }
        }

    }
}

BoardSystem/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoardSystem</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">BoardSystem</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Board" asp-action="Index">掲示板</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.Session.GetString("USER_LOGIN_KEY") == null)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">会員加入</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">ログイン</a></li>
                    }
                    else
                    {
                        <li><a>@Context.Session.GetString("USER_LOGIN_KEY")様</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">ログアウト</a></li>
                    }

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - BoardSystem</p>
        </footer>
    </div>
</body>
</html>